### ISSUE TITLE
ID connection on login

### ISSUE THREAD

**Issue by Intekai** [michielpost/Dfinity.Blazor#1]
Hello how read ID connection on login?

**Comment by michielpost** [comment]
Hi, there currently is no option to read the ID of the logged in user.
You can read/write values for a logged in user.

**Comment by Intekai** [comment]
Hello, thanks but when i put data    await DfinityServ.SetValueForUser("FMKeyXX12", "PippottoABCVVVVVV");  retirieve this error

   :32772/api/v2/canister/srlzz-jyaaa-aaaah-aaucq-cai/call:1     Failed to load resource: the server responded with a status of 400 ()

**Comment by michielpost** [comment]
It will only work when the application is deployed and running in a canister. See the deployed example here: https://syisf-7qaaa-aaaah-aauda-cai.ic0.app/

**Comment by Intekai** [comment]
i deploy it on docker linux but not work

**Comment by michielpost** [comment]
That won't work, please follow these instructions: https://internetcomputer.org/docs/current/developer-docs/

**Comment by Intekai** [comment]
sorry i don't understand how install Canister in Blazor system i use docker container linux please help me

**Comment by Intekai** [comment]
how Get Current Internet Identity?
I have to login and this works but then I can't read identifier for example with metamask I read wallet Get Current Internet Identity how do I read it? Thanks

**Comment by michielpost** [comment]
Hi, there currently is no option to read the ID of the logged in user.
You can read/write values for a logged in user.

For more information, please visit the Dfinity documentation and ask for help there.
https://internetcomputer.org/docs/current/developer-docs/
